pipeline{
   agent any 

   stages{
     stage('init') {          
            steps {
                sh 'terraform init -n--color'
             }
            }
             stage('validate') {          
            steps {
                sh 'terraform validate -n--color'
             }
            }
             stage('fmt') {          
            steps {
                sh 'terraform  -n-fmt-color'
             }
            }
            stage('plan') {          
            steps {
                sh 'terraform plan -n--color'
             }
            }
        }
   } 