pipeline{
   agent any 

   stages{
     stage('init') {          
            steps {
                sh 'terraform init -n--color'
             }
            }
             stage('validate') {          
            steps {
                sh 'terraform validate -n--color'
             }
            }
        }
   } 